char* types_list[]={
"GRIB1",
"GRIB2",
"reduced_gg_ml_grib2",
"reduced_gg_pl_grib1",
"reduced_gg_sfc_grib1",
"reduced_gg_ml_grib1",
"reduced_gg_pl_grib2",
"reduced_gg_sfc_grib2",
"reduced_gg_sfc_jpeg_grib2",
"reduced_ll_sfc_grib1",
"reduced_ll_sfc_grib2",
"regular_gg_ml_grib1",
"regular_gg_ml_grib2",
"regular_gg_pl_grib1",
"regular_gg_pl_grib2",
"regular_ll_sfc_grib1",
"regular_ll_sfc_grib2",
"regular_ll_pl_grib1",
"regular_ll_pl_grib2",
"sh_ml_grib1",
"sh_ml_grib2",
"sh_pl_grib1",
"sh_pl_grib2",
0};
int types_count=23;
