
#line 3 "lex.grib_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define grib_yyconst const
#else
#define grib_yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (grib_yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((grib_yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE grib_yyrestart(grib_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(grib_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct grib_yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int grib_yyleng;

extern FILE *grib_yyin, *grib_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		*grib_yy_cp = (grib_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(grib_yy_c_buf_p) = grib_yy_cp = grib_yy_bp + grib_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up grib_yytext again */ \
		} \
	while ( 0 )

#define unput(c) grib_yyunput( c, (grib_yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int grib_yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct grib_yy_buffer_state
	{
	FILE *grib_yy_input_file;

	char *grib_yy_ch_buf;		/* input buffer */
	char *grib_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	grib_yy_size_t grib_yy_buf_size;

	/* Number of characters read into grib_yy_ch_buf, not including EOB
	 * characters.
	 */
	int grib_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int grib_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int grib_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int grib_yy_at_bol;

    int grib_yy_bs_lineno; /**< The line count. */
    int grib_yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int grib_yy_fill_buffer;

	int grib_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via grib_yyrestart()), so that the user can continue scanning by
	 * just pointing grib_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t grib_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t grib_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * grib_yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (grib_yy_buffer_stack) \
                          ? (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (grib_yy_buffer_stack)[(grib_yy_buffer_stack_top)]

/* grib_yy_hold_char holds the character lost when grib_yytext is formed. */
static char grib_yy_hold_char;
static int grib_yy_n_chars;		/* number of characters read into grib_yy_ch_buf */
int grib_yyleng;

/* Points to current character in buffer. */
static char *grib_yy_c_buf_p = (char *) 0;
static int grib_yy_init = 0;		/* whether we need to initialize */
static int grib_yy_start = 0;	/* start state number */

/* Flag which is used to allow grib_yywrap()'s to do buffer switches
 * instead of setting up a fresh grib_yyin.  A bit of a hack ...
 */
static int grib_yy_did_buffer_switch_on_eof;

void grib_yyrestart (FILE *input_file  );
void grib_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE grib_yy_create_buffer (FILE *file,int size  );
void grib_yy_delete_buffer (YY_BUFFER_STATE b  );
void grib_yy_flush_buffer (YY_BUFFER_STATE b  );
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void grib_yypop_buffer_state (void );

static void grib_yyensure_buffer_stack (void );
static void grib_yy_load_buffer_state (void );
static void grib_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER grib_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE grib_yy_scan_buffer (char *base,grib_yy_size_t size  );
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char *grib_yy_str  );
YY_BUFFER_STATE grib_yy_scan_bytes (grib_yyconst char *bytes,int len  );

void *grib_yyalloc (grib_yy_size_t  );
void *grib_yyrealloc (void *,grib_yy_size_t  );
void grib_yyfree (void *  );

#define grib_yy_new_buffer grib_yy_create_buffer

#define grib_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive = is_interactive; \
	}

#define grib_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        grib_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->grib_yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *grib_yyin = (FILE *) 0, *grib_yyout = (FILE *) 0;

typedef int grib_yy_state_type;

extern int grib_yylineno;
extern char *grib_yytext;
#define grib_yytext_ptr grib_yytext

static grib_yy_state_type grib_yy_get_previous_state (void );
static grib_yy_state_type grib_yy_try_NUL_trans (grib_yy_state_type current_state  );
static int grib_yy_get_next_buffer (void );
static void grib_yy_fatal_error (grib_yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up grib_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(grib_yytext_ptr) = grib_yy_bp; \
	grib_yyleng = (size_t) (grib_yy_cp - grib_yy_bp); \
	(grib_yy_hold_char) = *grib_yy_cp; \
	*grib_yy_cp = '\0'; \
	(grib_yy_c_buf_p) = grib_yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct grib_yy_trans_info
	{
	flex_int32_t grib_yy_verify;
	flex_int32_t grib_yy_nxt;
	};
static grib_yyconst flex_int16_t grib_yy_accept[509] =
    {   0,
       97,   97,  101,   99,   97,   98,   10,   89,   96,   99,
       99,   99,   92,   99,   99,   99,   91,   91,   91,   90,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       99,   16,   97,    4,   12,   95,   94,    0,   93,   92,
        0,    3,    5,    1,    2,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   18,
       91,    8,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   13,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   14,
        0,   93,    0,    0,   95,   91,   19,   91,   11,   91,
       91,   91,    6,   53,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   30,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,    9,   91,   91,   42,   91,
       91,   91,   91,   91,   76,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,    0,   94,    0,
        0,   93,   91,   91,   91,   91,   91,   23,   91,   79,
       91,   91,   91,   91,   91,   91,   68,   91,   20,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   54,
       91,   91,   25,   91,   91,   91,   38,   91,   91,   91,
       91,   91,   15,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   87,   91,   91,   91,   91,   91,   91,   91,
       78,   91,   91,    0,   93,   91,   44,   91,   22,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       36,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       24,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   40,   91,   86,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   26,   84,   91,   85,

       64,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       61,   91,   91,   91,   91,   70,   91,   91,   91,   91,
       91,   63,   91,   37,   91,   57,   91,   91,   91,    7,
       91,   91,   91,   91,   91,   62,   91,   91,   33,   91,
       80,   91,   91,   91,   91,   91,   72,   91,   91,   91,
       82,   91,   91,   75,   81,   91,   55,   91,   91,   91,
       91,   91,   88,   91,   91,   91,   91,   52,   66,   69,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       29,   45,   91,   91,   91,   91,   91,   47,   91,   91,
       91,   91,   91,   31,   91,   51,   91,   91,   91,   74,

       91,   91,   46,   91,   91,   91,   91,   27,   91,   21,
       91,   34,   91,   91,   91,   91,   91,   91,   91,   32,
       91,   50,   17,   39,   91,   65,   91,   91,   91,   91,
       48,   91,   91,   91,   73,   91,   91,   91,   91,   91,
       91,   91,   77,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   56,   91,   91,   49,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   41,   91,   91,   71,   91,   83,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   43,   28,   91,   67,   91,   91,   91,   35,   91,

       59,   91,   91,   60,   91,   91,   58,    0
    } ;

static grib_yyconst flex_int32_t grib_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    7,    8,    1,
        1,    1,    9,    1,    9,   10,    1,   11,   12,   11,
       11,   13,   11,   11,   11,   11,   11,    1,    1,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   18,   17,
       19,   17,   20,   17,   17,   17,   21,   22,   17,   17,
       17,   17,   23,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   24,   25,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   17,   35,   36,   37,   38,
       39,   40,   17,   41,   42,   43,   44,   45,   46,   47,
       48,   17,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static grib_yyconst flex_int32_t grib_yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1
    } ;

static grib_yyconst flex_int16_t grib_yy_base[511] =
    {   0,
        0,    0,  364, 2061,  357, 2061,  342, 2061, 2061,  349,
       40,   43,   48,   47,  339,  320,   56,   59,   62, 2061,
       69,   74,   77,   80,   83,   59,  115,  120,  128,   62,
      123,  111,  112,  161,  149,  113,  150,  169,  200,  203,
      284, 2061,  330, 2061, 2061,  209,  212,  220,  234,  244,
      254, 2061, 2061, 2061, 2061,    0,  237,  247,  260,  264,
      267,  270,  273,  276,  281,  291,  125,  271,  305,  309,
      313,  318,  326,  329,  332,  303,  337,  340,  350,  359,
      362,  370,  373,  376,  380,  383,  386,  397,  389,  400,
      404,  407,  411,  414,  426,  429,  433,  440,  450,  453,

      456,  459,  466,  471,  478,  152,  469,  480,  483, 2061,
      489,  512,  520,  515,  523,  526,  532,  535,  539,  542,
      545,  551,  554,  557,  562,  565,  571,  574,  582,  585,
      594,  597,  603,  606,  617,  613,  620,  623,  167,  627,
      633,  639,  649,  654,  659,  662,  665,  668,  671,  677,
      687,  693,  696,  702,  709,  712,  715,  720,  723,  733,
      736,  741,  744,  747,  751,  760,  765,  768,  773,  780,
      776,  783,  788,  795,  798,  806,  810,  814,  819,  826,
      832,  835,  838,  843,  848,  853,  856,  859,  862,  865,
      868,  871,  879,  882,  888,  891,  902,  905,  908,  911,

      915,  297,  284,  282,  918,  925,  932,  921,  938,  942,
      947,  955,  958,  961,  964,  968,  975,  979,  982,  988,
      991,  994, 1002, 1007, 1010, 1013, 1018, 1021, 1024, 1028,
     1039, 1042, 1031, 1046, 1052, 1055, 1062, 1070, 1074, 1077,
     1081, 1084, 1087, 1094, 1099, 1107, 1110, 1113, 1119, 1122,
     1125, 1128, 1132, 1135, 1138, 1145, 1155, 1148, 1158, 1161,
     1165,  270,  263,  271, 1169, 1177, 1181, 1185, 1191,  267,
     1197, 1200, 1207, 1211, 1214, 1217, 1224, 1227, 1234, 1241,
     1244, 1249, 1258, 1261, 1264, 1269, 1276, 1282, 1285, 1293,
     1289, 1297, 1300, 1305, 1315, 1318, 1325, 1331, 1334, 1337,

     1346, 1349, 1352, 1355, 1358, 1365, 1369, 1372, 1375, 1378,
     1381, 1385,  264,  248,  226, 1393, 1397, 1400, 1408, 1413,
      221, 1418, 1421, 1424, 1429, 1432, 1435, 1438, 1445, 1448,
     1451, 1454, 1459, 1462, 1471, 1476, 1479, 1482, 1485, 1494,
     1499, 1503, 1508, 1511, 1514, 1517, 1520, 1523, 1528, 1531,
     1537, 1546, 1554, 1557, 1560, 1563, 1566,  237,  225,  209,
     1569, 1572, 1579, 1582,  201, 1588, 1591, 1594, 1597, 1602,
     1605, 1608, 1613, 1618, 1628, 1631, 1634, 1639, 1646, 1650,
     1654, 1657, 1660, 1666, 1672, 1679, 1682, 1685, 1692, 1697,
      213,  205,  196, 1700, 1703, 1706,  189, 1710, 1713, 1716,

     1720, 1723, 1736, 1739, 1742, 1749, 1752, 1756, 1759, 1762,
     1765, 1773, 1777, 1780, 1783, 1792,  181,  198,  188, 1786,
      187, 1797, 1800, 1809, 1812, 1816, 1822, 1825, 1828, 1831,
     1838, 1841, 1844, 1847, 1851, 1854,  164,  181,  188,  157,
     1859, 1863, 1868, 1874, 1877, 1883, 1889, 1894, 1897,  167,
      158,  168,    0, 1900, 1910, 1915, 1918, 1921, 1929, 1932,
     1935,  163,  151,  141, 1940, 1943, 1949, 1952, 1967, 1970,
     1974,  141,  122,  118, 1977, 1983, 1986, 1989, 1996, 1999,
     2002,  105,  108,   91, 2005, 2013, 2016, 2019,   91,   75,
       85, 2022, 2027, 2030, 2033,   85,   81,   63, 2042,   63,

        0,   51,   47,    0,   51,   44,    0, 2061,   63,   62
    } ;

static grib_yyconst flex_int16_t grib_yy_def[511] =
    {   0,
      508,    1,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  509,  509,  509,  508,
      509,  509,  509,  509,   21,   21,  509,  509,   21,   21,
      509,   31,   31,  509,   31,   31,   31,   31,  509,  509,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  510,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,   21,   21,  509,  509,
      509,  509,  509,  509,  509,  510,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,

      509,  509,  509,  509,  509,   31,   31,   31,   31,  508,
      508,  508,  508,  508,  508,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  510,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  508,  508,  508,
      508,  508,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,

      509,  510,  510,  510,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  508,  508,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  510,  510,  510,  509,  509,  509,  509,  509,  510,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  510,  510,  510,  509,  509,  509,  509,  509,
      510,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  510,  510,  510,
      509,  509,  509,  509,  510,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      510,  510,  510,  509,  509,  509,  510,  509,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  510,  510,  510,  509,
      510,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  510,  510,  510,  510,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  510,
      510,  510,  510,  509,  509,  509,  509,  509,  509,  509,
      509,  510,  510,  510,  509,  509,  509,  509,  509,  509,
      509,  510,  510,  510,  509,  509,  509,  509,  509,  509,
      509,  510,  510,  510,  509,  509,  509,  509,  510,  510,
      510,  509,  509,  509,  509,  510,  510,  510,  509,  510,

      510,  510,  510,  510,  510,  510,  510,    0,  508,  508
    } ;

static grib_yyconst flex_int16_t grib_yy_nxt[2112] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    8,   11,   12,
       13,   13,   13,   14,   15,   16,   17,   17,   17,   17,
       18,   17,   17,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   17,   40,   17,   17,   41,   42,
       46,   46,   46,   47,   47,   47,   48,   49,   50,   50,
       50,   52,   53,   56,   57,   51,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  507,  506,   51,   58,   56,
       56,   56,  505,  504,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  503,   75,   59,   57,   57,   57,   57,

       57,   57,   67,   84,   60,  502,   61,   64,   62,   69,
       63,   71,   65,  501,  500,   68,  498,  497,   72,  496,
       73,   66,   57,   70,   57,   56,   76,   56,  491,   74,
       56,   56,   56,   56,   56,   56,   57,   57,   57,  490,
       89,   91,   99,  489,   57,   57,   57,  484,   85,   90,
       92,   57,   86,   77,   78,   93,   87,   79,   80,  483,
       57,   88,  126,   57,   57,   81,  127,   57,  482,   82,
       83,   56,   56,   56,   96,   57,  474,  171,   57,  100,
      473,   57,   57,  101,  102,  172,  472,   97,   57,   98,
       57,  464,  103,  463,   57,  104,  462,  453,  105,  202,

      452,   94,   57,  203,  451,   95,  450,   57,  204,  106,
       56,   56,   56,   56,   56,   56,  440,   48,   49,   46,
       46,   46,   47,   47,   47,  439,   51,  438,  437,  111,
       46,   46,   46,  421,  419,  108,  418,  107,   51,  417,
      397,  111,  393,  109,  112,  112,  112,   56,   56,   56,
      392,  113,   48,   49,   50,   50,   50,   56,   56,   56,
      391,   51,  114,  113,  115,  115,  115,  365,  360,  116,
       56,   56,   56,   51,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  359,
      117,   56,   56,   56,  358,  119,  321,  118,  315,  128,

      121,   56,   56,   56,  314,  313,   57,  129,  130,  120,
      131,  264,   57,  263,  122,   56,   56,   56,  123,   56,
       56,   56,  262,   56,   56,   56,  139,  124,   56,   56,
       56,   43,  110,  125,   55,  132,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  133,  134,   56,   56,   56,
       56,   56,   56,   54,  136,   45,   44,  138,   43,  135,
       56,   56,   56,  508,  508,  140,  508,  508,  137,   56,
       56,   56,   56,   56,   56,  508,  141,  508,  508,  142,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  143,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,  144,  508,  508,  145,  146,   56,   56,   56,
       56,   56,   56,  508,   56,   56,   56,   56,   56,   56,
      147,   56,   56,   56,   56,   56,   56,  148,  153,  154,
      155,  152,  508,  508,  149,  150,   56,   56,   56,   56,
       56,   56,  151,   56,   56,   56,  157,  508,  508,  156,
       56,   56,   56,  508,  508,  158,  508,  159,  508,  508,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,  508,  161,  160,  162,   56,   56,   56,  508,
      164,   56,   56,   56,  508,  508,  163,  166,   56,   56,
       56,  508,  167,  508,  173,  165,  508,  178,   57,  179,

      179,  179,   57,  508,  169,   57,  168,   57,   57,  175,
      174,  508,   57,  176,  170,  508,  177,  508,   57,  508,
      508,   57,  112,  112,  112,  115,  115,  115,  181,  180,
      182,  182,  182,  115,  115,  115,   56,   56,   56,  508,
      508,  180,   56,   56,   56,   56,   56,   56,  183,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  508,  508,
      184,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      508,  185,   56,   56,   56,   56,   56,   56,  186,  508,
      187,   56,   56,   56,   56,   56,   56,  508,  189,  508,
      508,  188,   56,   56,   56,   56,   56,   56,  508,  508,

      190,  508,  508,  191,   56,   56,   56,   56,   56,   56,
      508,  508,  193,   56,   56,   56,   56,   56,   56,  508,
      508,  192,  196,   56,   56,   56,  194,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  508,   56,   56,   56,
      508,  195,  197,   56,   56,   56,  199,  508,  198,   56,
       56,   56,  508,  508,  201,  205,  508,  508,  200,   56,
       56,   56,  508,  206,   56,   56,   56,  508,  207,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  208,  508,  210,   56,   56,   56,
      508,  211,  508,  508,  209,  508,  212,   56,   56,   56,

      508,  508,  214,   56,   56,   56,   56,   56,   56,  508,
      213,  215,   56,   56,   56,  508,  216,  508,  217,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  508,  218,
       56,   56,   56,   56,   56,   56,  220,  508,  222,  221,
      508,  508,  219,   56,   56,   56,   56,   56,   56,  508,
      223,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      224,   56,   56,   56,  508,  225,  226,  508,  508,  228,
       56,   56,   56,  227,  231,   56,   56,   56,   56,   56,
       56,  508,  229,   56,   56,   56,   56,   56,   56,  230,
       56,   56,   56,   56,   56,   56,  508,  232,   56,   56,

       56,  234,  508,  508,  233,   56,   56,   56,   56,   56,
       56,  508,  508,  237,  238,  235,   56,   56,   56,  236,
       56,   56,   56,  239,  179,  179,  179,  508,  240,  179,
      179,  179,  508,  508,  244,  241,  245,  245,  245,  508,
      508,  242,  182,  182,  182,  182,  182,  182,   56,   56,
       56,  508,  243,   56,   56,   56,  508,  246,   56,   56,
       56,  508,  508,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  247,  248,  249,  508,  251,   56,
       56,   56,   56,   56,   56,  508,  250,  508,   56,   56,

       56,   56,   56,   56,  508,  508,  253,  508,  254,  508,
      252,  256,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  255,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  257,   56,   56,   56,  258,  508,
      508,  260,   56,   56,   56,  508,  508,  265,   56,   56,
       56,  259,   56,  270,   56,  508,  261,   56,   56,   56,
      266,  508,  267,  269,  268,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  508,   56,   56,
       56,  508,  271,  508,  273,   56,   56,   56,  508,   56,
       56,   56,   56,   56,   56,  508,  508,  272,   56,   56,

       56,   56,   56,   56,   56,   56,   56,  274,  275,  276,
      508,  277,   56,   56,   56,  508,  279,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  278,  280,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  508,   56,   56,
       56,   56,   56,   56,  285,  508,  508,  281,  282,   56,
       56,   56,   56,   56,   56,  283,   56,   56,   56,  508,
      284,  287,   56,   56,   56,   56,   56,   56,  286,  508,
      508,  289,   56,   56,   56,  508,  288,  508,  508,  291,
       56,   56,   56,  290,   56,   56,   56,   56,   56,   56,
      292,   56,   56,   56,   56,   56,   56,   56,   56,   56,

      508,  294,  508,  293,  245,  245,  245,  295,  296,  245,
      245,  245,  508,  297,  508,  508,  298,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  508,  508,  299,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  300,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  508,  508,  303,  302,   56,   56,   56,   56,   56,
       56,  304,  508,  306,  301,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  305,   56,   56,   56,  307,   56,
       56,   56,  508,  308,  508,  508,  310,   56,   56,   56,
      309,   56,   56,   56,  312,   56,   56,   56,  508,  508,

      311,   56,   56,   56,  508,  508,  316,   56,   56,   56,
       56,   56,   56,  319,  508,  317,  318,   56,   56,   56,
      508,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      508,  508,  322,  320,   56,   56,   56,   56,   56,   56,
      508,  325,  508,  508,   56,   56,   56,  508,  508,  323,
      324,   56,   56,   56,   56,   56,   56,  508,  508,   56,
       56,   56,  508,  508,  326,  327,  328,  329,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  331,  332,   56,
       56,   56,  508,  330,  508,  333,   56,   56,   56,  508,
      508,  334,   56,   56,   56,   56,   56,   56,  336,   56,

       56,   56,  335,   56,   56,   56,  508,   56,   56,   56,
       56,   56,   56,  339,  337,   56,   56,   56,  508,  508,
      338,  341,  342,  508,  340,   56,   56,   56,   56,   56,
       56,  508,  508,  343,  344,   56,   56,   56,  508,  508,
      345,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      508,  508,  347,  508,  508,  346,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  508,  348,  508,  508,   56,   56,   56,  349,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  353,   56,   56,   56,  508,  508,

      351,  350,  352,   56,   56,   56,  354,   56,   56,   56,
       56,   56,   56,  508,  508,  356,  508,  355,   56,   56,
       56,  508,  361,   56,   56,   56,  508,  357,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  363,  362,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  364,  508,  508,  367,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  508,  366,   56,
       56,   56,   56,   56,   56,  508,  508,  368,  508,  371,
      370,   56,   56,   56,  508,  369,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  372,  508,

      374,  508,  373,  508,   56,   56,   56,  508,  375,   56,
       56,   56,  377,   56,   56,   56,  376,  378,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  508,  380,   56,   56,
       56,   56,   56,   56,  508,  379,  383,   56,   56,   56,
      508,  381,  508,  508,  386,  382,   56,   56,   56,  384,
      387,  508,  508,  385,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  508,  390,  389,  388,   56,
       56,   56,   56,   56,   56,  508,  508,  395,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      508,  394,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  508,  396,   56,   56,   56,  508,  398,   56,   56,
       56,  508,  399,  508,  400,  508,  508,  401,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  508,  402,   56,
       56,   56,  508,  508,  405,  403,   56,   56,   56,  406,
       56,   56,   56,  404,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  508,  508,  408,   56,   56,   56,  508,
      508,  407,   56,   56,   56,  508,  508,  409,  410,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  508,  411,

      508,  412,   56,   56,   56,  508,  413,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  414,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  415,
       56,   56,   56,   56,   56,   56,  508,  508,  416,  422,
      508,  508,  423,  508,  508,  420,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  508,  508,  424,  508,   56,
       56,   56,   56,   56,   56,  425,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  508,  430,
      508,  427,  428,   56,   56,   56,  426,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,  429,

      508,  431,   56,   56,   56,  508,  432,   56,   56,   56,
       56,   56,   56,  508,  508,  433,  508,  508,  434,   56,
       56,   56,   56,   56,   56,  435,   56,   56,   56,  508,
      508,  436,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  508,  441,  508,  442,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
      443,   56,   56,   56,   56,   56,   56,  444,  445,   56,
       56,   56,  447,   56,   56,   56,  508,  448,   56,   56,
       56,  508,  446,  449,   56,   56,   56,   56,   56,   56,
      508,  455,  508,   56,   56,   56,  508,  508,  454,   56,

       56,   56,  508,  456,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  508,  508,  457,  458,  508,  459,  460,
       56,   56,   56,  508,  461,   56,   56,   56,   56,   56,
       56,   56,   56,   56,  508,  465,  508,  508,  466,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  467,  508,
       56,   56,   56,   56,   56,   56,  508,  508,  468,   56,
       56,   56,   56,   56,   56,  470,  508,  508,  471,  475,
      508,  469,  508,  508,  477,  508,  476,   56,   56,   56,
       56,   56,   56,  478,   56,   56,   56,   56,   56,   56,
      508,  508,  479,   56,   56,   56,   56,   56,   56,   56,

       56,   56,  508,  508,  481,  480,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,  508,  486,
      485,  508,  487,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,  488,  492,   56,   56,   56,
       56,   56,   56,   56,   56,   56,  495,  508,  493,  508,
      508,  494,   56,   56,   56,  508,  508,  508,  508,  499,
        3,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,

      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508
    } ;

static grib_yyconst flex_int16_t grib_yy_chk[2112] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       11,   11,   11,   12,   12,   12,   13,   13,   13,   13,
       13,   14,   14,  510,  509,   13,   17,   17,   17,   18,
       18,   18,   19,   19,   19,  506,  505,   13,   18,   21,
       21,   21,  503,  502,   22,   22,   22,   23,   23,   23,
       24,   24,   24,  500,   26,   19,   26,   30,   26,   30,

       26,   30,   23,   30,   21,  498,   21,   22,   21,   24,
       21,   25,   22,  497,  496,   23,  491,  490,   25,  489,
       25,   22,   25,   24,   25,   27,   27,   27,  484,   25,
       28,   28,   28,   31,   31,   31,   32,   33,   36,  483,
       32,   33,   36,  482,   32,   33,   36,  474,   31,   32,
       33,   36,   31,   28,   29,   33,   31,   29,   29,  473,
       67,   31,   67,   29,   67,   29,   67,   29,  472,   29,
       29,   34,   34,   34,   35,   37,  464,  106,   35,   37,
      463,  106,   35,   37,   37,  106,  462,   35,   37,   35,
      106,  452,   37,  451,   38,   37,  450,  440,   38,  139,

      439,   34,   38,  139,  438,   34,  437,   38,  139,   38,
       39,   39,   39,   40,   40,   40,  421,   46,   46,   46,
       46,   46,   47,   47,   47,  419,   46,  418,  417,   47,
       48,   48,   48,  397,  393,   40,  392,   39,   46,  391,
      365,   47,  360,   40,   49,   49,   49,   57,   57,   57,
      359,   49,   50,   50,   50,   50,   50,   58,   58,   58,
      358,   50,   51,   49,   51,   51,   51,  321,  315,   58,
       59,   59,   59,   50,   60,   60,   60,   61,   61,   61,
       62,   62,   62,   63,   63,   63,   64,   64,   64,  314,
       59,   65,   65,   65,  313,   61,  270,   60,  264,   68,

       63,   66,   66,   66,  263,  262,   68,   68,   68,   62,
       68,  204,   68,  203,   63,   69,   69,   69,   64,   70,
       70,   70,  202,   71,   71,   71,   76,   65,   72,   72,
       72,   43,   41,   66,   16,   69,   73,   73,   73,   74,
       74,   74,   75,   75,   75,   70,   71,   77,   77,   77,
       78,   78,   78,   15,   73,   10,    7,   75,    5,   72,
       79,   79,   79,    3,    0,   77,    0,    0,   74,   80,
       80,   80,   81,   81,   81,    0,   78,    0,    0,   79,
       82,   82,   82,   83,   83,   83,   84,   84,   84,   81,
       85,   85,   85,   86,   86,   86,   87,   87,   87,   89,

       89,   89,   83,    0,    0,   84,   85,   88,   88,   88,
       90,   90,   90,    0,   91,   91,   91,   92,   92,   92,
       86,   93,   93,   93,   94,   94,   94,   87,   90,   91,
       92,   89,    0,    0,   88,   88,   95,   95,   95,   96,
       96,   96,   88,   97,   97,   97,   93,    0,    0,   92,
       98,   98,   98,    0,    0,   95,    0,   96,    0,    0,
       99,   99,   99,  100,  100,  100,  101,  101,  101,  102,
      102,  102,    0,   98,   97,   99,  103,  103,  103,    0,
      100,  104,  104,  104,    0,    0,   99,  101,  105,  105,
      105,    0,  102,    0,  107,  100,    0,  111,  107,  111,

      111,  111,  107,    0,  104,  108,  103,  107,  109,  108,
      107,    0,  109,  108,  105,    0,  109,    0,  108,    0,
        0,  109,  112,  112,  112,  114,  114,  114,  113,  112,
      113,  113,  113,  115,  115,  115,  116,  116,  116,    0,
        0,  112,  117,  117,  117,  118,  118,  118,  116,  119,
      119,  119,  120,  120,  120,  121,  121,  121,    0,    0,
      118,  122,  122,  122,  123,  123,  123,  124,  124,  124,
        0,  120,  125,  125,  125,  126,  126,  126,  121,    0,
      122,  127,  127,  127,  128,  128,  128,    0,  126,    0,
        0,  125,  129,  129,  129,  130,  130,  130,    0,    0,

      127,    0,    0,  128,  131,  131,  131,  132,  132,  132,
        0,    0,  130,  133,  133,  133,  134,  134,  134,    0,
        0,  129,  132,  136,  136,  136,  130,  135,  135,  135,
      137,  137,  137,  138,  138,  138,    0,  140,  140,  140,
        0,  131,  133,  141,  141,  141,  135,    0,  134,  142,
      142,  142,    0,    0,  138,  140,    0,    0,  137,  143,
      143,  143,    0,  141,  144,  144,  144,    0,  142,  145,
      145,  145,  146,  146,  146,  147,  147,  147,  148,  148,
      148,  149,  149,  149,  143,    0,  145,  150,  150,  150,
        0,  146,    0,    0,  144,    0,  147,  151,  151,  151,

        0,    0,  149,  152,  152,  152,  153,  153,  153,    0,
      148,  150,  154,  154,  154,    0,  151,    0,  152,  155,
      155,  155,  156,  156,  156,  157,  157,  157,    0,  153,
      158,  158,  158,  159,  159,  159,  155,    0,  156,  155,
        0,    0,  154,  160,  160,  160,  161,  161,  161,    0,
      157,  162,  162,  162,  163,  163,  163,  164,  164,  164,
      158,  165,  165,  165,    0,  159,  160,    0,    0,  162,
      166,  166,  166,  161,  165,  167,  167,  167,  168,  168,
      168,    0,  163,  169,  169,  169,  171,  171,  171,  164,
      170,  170,  170,  172,  172,  172,    0,  166,  173,  173,

      173,  168,    0,    0,  167,  174,  174,  174,  175,  175,
      175,    0,    0,  171,  172,  169,  176,  176,  176,  170,
      177,  177,  177,  173,  178,  178,  178,    0,  174,  179,
      179,  179,    0,    0,  180,  175,  180,  180,  180,    0,
        0,  176,  181,  181,  181,  182,  182,  182,  183,  183,
      183,    0,  177,  184,  184,  184,    0,  183,  185,  185,
      185,    0,    0,  186,  186,  186,  187,  187,  187,  188,
      188,  188,  189,  189,  189,  190,  190,  190,  191,  191,
      191,  192,  192,  192,  184,  185,  186,    0,  189,  193,
      193,  193,  194,  194,  194,    0,  187,    0,  195,  195,

      195,  196,  196,  196,    0,    0,  192,    0,  193,    0,
      191,  195,  197,  197,  197,  198,  198,  198,  199,  199,
      199,  200,  200,  200,  194,  201,  201,  201,  205,  205,
      205,  208,  208,  208,  196,  206,  206,  206,  198,    0,
        0,  201,  207,  207,  207,    0,    0,  205,  209,  209,
      209,  200,  210,  210,  210,    0,  201,  211,  211,  211,
      206,    0,  207,  209,  208,  212,  212,  212,  213,  213,
      213,  214,  214,  214,  215,  215,  215,    0,  216,  216,
      216,    0,  211,    0,  214,  217,  217,  217,    0,  218,
      218,  218,  219,  219,  219,    0,    0,  212,  220,  220,

      220,  221,  221,  221,  222,  222,  222,  215,  216,  218,
        0,  219,  223,  223,  223,    0,  221,  224,  224,  224,
      225,  225,  225,  226,  226,  226,  220,  222,  227,  227,
      227,  228,  228,  228,  229,  229,  229,    0,  230,  230,
      230,  233,  233,  233,  228,    0,    0,  224,  225,  231,
      231,  231,  232,  232,  232,  226,  234,  234,  234,    0,
      227,  230,  235,  235,  235,  236,  236,  236,  229,    0,
        0,  232,  237,  237,  237,    0,  231,    0,    0,  235,
      238,  238,  238,  234,  239,  239,  239,  240,  240,  240,
      236,  241,  241,  241,  242,  242,  242,  243,  243,  243,

        0,  238,    0,  237,  244,  244,  244,  239,  240,  245,
      245,  245,    0,  242,    0,    0,  243,  246,  246,  246,
      247,  247,  247,  248,  248,  248,    0,    0,  246,  249,
      249,  249,  250,  250,  250,  251,  251,  251,  252,  252,
      252,  248,  253,  253,  253,  254,  254,  254,  255,  255,
      255,    0,    0,  252,  251,  256,  256,  256,  258,  258,
      258,  253,    0,  255,  250,  257,  257,  257,  259,  259,
      259,  260,  260,  260,  254,  261,  261,  261,  255,  265,
      265,  265,    0,  256,    0,    0,  258,  266,  266,  266,
      257,  267,  267,  267,  260,  268,  268,  268,    0,    0,

      259,  269,  269,  269,    0,    0,  265,  271,  271,  271,
      272,  272,  272,  268,    0,  266,  267,  273,  273,  273,
        0,  274,  274,  274,  275,  275,  275,  276,  276,  276,
        0,    0,  272,  269,  277,  277,  277,  278,  278,  278,
        0,  275,    0,    0,  279,  279,  279,    0,    0,  273,
      274,  280,  280,  280,  281,  281,  281,    0,    0,  282,
      282,  282,    0,    0,  276,  277,  278,  279,  283,  283,
      283,  284,  284,  284,  285,  285,  285,  281,  282,  286,
      286,  286,    0,  280,    0,  282,  287,  287,  287,    0,
        0,  283,  288,  288,  288,  289,  289,  289,  286,  291,

      291,  291,  285,  290,  290,  290,    0,  292,  292,  292,
      293,  293,  293,  289,  287,  294,  294,  294,    0,    0,
      288,  291,  292,    0,  290,  295,  295,  295,  296,  296,
      296,    0,    0,  293,  294,  297,  297,  297,    0,    0,
      295,  298,  298,  298,  299,  299,  299,  300,  300,  300,
        0,    0,  299,    0,    0,  296,  301,  301,  301,  302,
      302,  302,  303,  303,  303,  304,  304,  304,  305,  305,
      305,    0,  302,    0,    0,  306,  306,  306,  303,  307,
      307,  307,  308,  308,  308,  309,  309,  309,  310,  310,
      310,  311,  311,  311,  307,  312,  312,  312,    0,    0,

      305,  304,  306,  316,  316,  316,  308,  317,  317,  317,
      318,  318,  318,    0,    0,  310,    0,  309,  319,  319,
      319,    0,  317,  320,  320,  320,    0,  312,  322,  322,
      322,  323,  323,  323,  324,  324,  324,  319,  318,  325,
      325,  325,  326,  326,  326,  327,  327,  327,  328,  328,
      328,  320,    0,    0,  325,  329,  329,  329,  330,  330,
      330,  331,  331,  331,  332,  332,  332,    0,  323,  333,
      333,  333,  334,  334,  334,    0,    0,  327,    0,  331,
      329,  335,  335,  335,    0,  328,  336,  336,  336,  337,
      337,  337,  338,  338,  338,  339,  339,  339,  332,    0,

      334,    0,  333,    0,  340,  340,  340,    0,  335,  341,
      341,  341,  338,  342,  342,  342,  337,  340,  343,  343,
      343,  344,  344,  344,  345,  345,  345,  346,  346,  346,
      347,  347,  347,  348,  348,  348,    0,  343,  349,  349,
      349,  350,  350,  350,    0,  342,  346,  351,  351,  351,
        0,  344,    0,    0,  350,  345,  352,  352,  352,  348,
      351,    0,    0,  349,  353,  353,  353,  354,  354,  354,
      355,  355,  355,  356,  356,  356,  357,  357,  357,  361,
      361,  361,  362,  362,  362,    0,  356,  353,  352,  363,
      363,  363,  364,  364,  364,    0,    0,  362,  366,  366,

      366,  367,  367,  367,  368,  368,  368,  369,  369,  369,
        0,  361,  370,  370,  370,  371,  371,  371,  372,  372,
      372,    0,  364,  373,  373,  373,    0,  366,  374,  374,
      374,    0,  367,    0,  371,    0,    0,  372,  375,  375,
      375,  376,  376,  376,  377,  377,  377,    0,  373,  378,
      378,  378,    0,    0,  376,  374,  379,  379,  379,  377,
      380,  380,  380,  375,  381,  381,  381,  382,  382,  382,
      383,  383,  383,    0,    0,  379,  384,  384,  384,    0,
        0,  378,  385,  385,  385,    0,    0,  380,  383,  386,
      386,  386,  387,  387,  387,  388,  388,  388,    0,  384,

        0,  385,  389,  389,  389,    0,  386,  390,  390,  390,
      394,  394,  394,  395,  395,  395,  396,  396,  396,  387,
      398,  398,  398,  399,  399,  399,  400,  400,  400,  389,
      401,  401,  401,  402,  402,  402,    0,    0,  390,  398,
        0,    0,  399,    0,    0,  395,  403,  403,  403,  404,
      404,  404,  405,  405,  405,    0,    0,  401,    0,  406,
      406,  406,  407,  407,  407,  402,  408,  408,  408,  409,
      409,  409,  410,  410,  410,  411,  411,  411,    0,  408,
        0,  405,  406,  412,  412,  412,  404,  413,  413,  413,
      414,  414,  414,  415,  415,  415,  420,  420,  420,  407,

        0,  409,  416,  416,  416,    0,  411,  422,  422,  422,
      423,  423,  423,    0,    0,  413,    0,    0,  414,  424,
      424,  424,  425,  425,  425,  415,  426,  426,  426,    0,
        0,  416,  427,  427,  427,  428,  428,  428,  429,  429,
      429,  430,  430,  430,    0,  425,    0,  427,  431,  431,
      431,  432,  432,  432,  433,  433,  433,  434,  434,  434,
      428,  435,  435,  435,  436,  436,  436,  429,  430,  441,
      441,  441,  433,  442,  442,  442,    0,  434,  443,  443,
      443,    0,  432,  436,  444,  444,  444,  445,  445,  445,
        0,  442,    0,  446,  446,  446,    0,    0,  441,  447,

      447,  447,    0,  444,  448,  448,  448,  449,  449,  449,
      454,  454,  454,    0,    0,  445,  446,    0,  447,  448,
      455,  455,  455,    0,  449,  456,  456,  456,  457,  457,
      457,  458,  458,  458,    0,  454,    0,    0,  455,  459,
      459,  459,  460,  460,  460,  461,  461,  461,  457,    0,
      465,  465,  465,  466,  466,  466,    0,    0,  458,  467,
      467,  467,  468,  468,  468,  460,    0,    0,  461,  465,
        0,  459,    0,    0,  467,    0,  466,  469,  469,  469,
      470,  470,  470,  468,  471,  471,  471,  475,  475,  475,
        0,    0,  469,  476,  476,  476,  477,  477,  477,  478,

      478,  478,    0,    0,  471,  470,  479,  479,  479,  480,
      480,  480,  481,  481,  481,  485,  485,  485,    0,  477,
      476,    0,  479,  486,  486,  486,  487,  487,  487,  488,
      488,  488,  492,  492,  492,  481,  485,  493,  493,  493,
      494,  494,  494,  495,  495,  495,  488,    0,  486,    0,
        0,  487,  499,  499,  499,    0,    0,    0,    0,  494,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,

      508,  508,  508,  508,  508,  508,  508,  508,  508,  508,
      508
    } ;

static grib_yy_state_type grib_yy_last_accepting_state;
static char *grib_yy_last_accepting_cpos;

extern int grib_yy_flex_debug;
int grib_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define grib_yymore() grib_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *grib_yytext;
#line 1 "gribl.l"
/**
* Copyright 2005-2007 ECMWF
*
* Licensed under the GNU Lesser General Public License which
* incorporates the terms and conditions of version 3 of the GNU
* General Public License.
* See LICENSE and gpl-3.0.txt for details.
*/
#line 12 "gribl.l"
#include "grib_api_internal.h"
#include "grib_yacc.h"
#include <ctype.h>

int grib_yylineno;

/* Keep -Wall quiet */


/*

This is needed for implementing "include", otherwise
flex buffer optimization break the includes.

*/

#define YY_INPUT(buf,result,max_size) \
        { \
        int c = getc(grib_yyin); \
        result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
        }


/*
#ifdef __GNUC__
#ifdef FLEX_SCANNER
void grib_yyunput (int c,char *buf_ptr  );
void _grib_ignore_grib_yyunput_unused_error() { grib_yyunput(0,0); }
#endif
#endif
*/

#line 1124 "lex.grib_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int grib_yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int grib_yywrap (void );
#else
extern int grib_yywrap (void );
#endif
#endif

    void grib_yyunput (int c,char *buf_ptr  );
    
#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char *,grib_yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int grib_yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( grib_yytext, grib_yyleng, 1, grib_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( grib_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( grib_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, grib_yyin))==0 && ferror(grib_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(grib_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "grib_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef grib_yyterminate
#define grib_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) grib_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int grib_yylex (void);

#define YY_DECL int grib_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after grib_yytext and grib_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp, *grib_yy_bp;
	register int grib_yy_act;
    
#line 58 "gribl.l"



#line 1281 "lex.grib_yy.c"

	if ( !(grib_yy_init) )
		{
		(grib_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (grib_yy_start) )
			(grib_yy_start) = 1;	/* first start state */

		if ( ! grib_yyin )
			grib_yyin = stdin;

		if ( ! grib_yyout )
			grib_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			grib_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
		}

		grib_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		grib_yy_cp = (grib_yy_c_buf_p);

		/* Support of grib_yytext. */
		*grib_yy_cp = (grib_yy_hold_char);

		/* grib_yy_bp points to the position in grib_yy_ch_buf of the start of
		 * the current run.
		 */
		grib_yy_bp = grib_yy_cp;

		grib_yy_current_state = (grib_yy_start);
grib_yy_match:
		do
			{
			register YY_CHAR grib_yy_c = grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)];
			if ( grib_yy_accept[grib_yy_current_state] )
				{
				(grib_yy_last_accepting_state) = grib_yy_current_state;
				(grib_yy_last_accepting_cpos) = grib_yy_cp;
				}
			while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
				{
				grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
				if ( grib_yy_current_state >= 509 )
					grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
				}
			grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
			++grib_yy_cp;
			}
		while ( grib_yy_base[grib_yy_current_state] != 2061 );

grib_yy_find_action:
		grib_yy_act = grib_yy_accept[grib_yy_current_state];
		if ( grib_yy_act == 0 )
			{ /* have to back up */
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			grib_yy_act = grib_yy_accept[grib_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( grib_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*grib_yy_cp = (grib_yy_hold_char);
			grib_yy_cp = (grib_yy_last_accepting_cpos);
			grib_yy_current_state = (grib_yy_last_accepting_state);
			goto grib_yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "gribl.l"
return EQ       ;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "gribl.l"
return GE       ;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "gribl.l"
return LE       ;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "gribl.l"
return NE       ;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "gribl.l"
return NE       ;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "gribl.l"
return BIT      ;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "gribl.l"
return BITOFF   ;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "gribl.l"
return IS   ;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "gribl.l"
return NOT   ;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "gribl.l"
return NOT   ;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "gribl.l"
return AND   ;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "gribl.l"
return AND   ;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "gribl.l"
return OR   ;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "gribl.l"
return OR   ;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "gribl.l"
return NIL   ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "gribl.l"
return DUMMY   ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "gribl.l"
return LOWERCASE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "gribl.l"
return IF       ;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "gribl.l"
return IF_TRANSIENT       ;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "gribl.l"
return ELSE       ;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 84 "gribl.l"
return UNSIGNED ;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "gribl.l"
return ASCII    ;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "gribl.l"
return BYTE    ;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 87 "gribl.l"
return LABEL    ;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "gribl.l"
return LIST     ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 89 "gribl.l"
return WHILE     ;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "gribl.l"
return TEMPLATE ;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "gribl.l"
return TEMPLATE_NOFAIL ;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 92 "gribl.l"
return TRIGGER ;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 93 "gribl.l"
return END      ;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 94 "gribl.l"
return IBMFLOAT ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "gribl.l"
return FLOAT ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 96 "gribl.l"
return SIGNED   ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "gribl.l"
return CODETABLE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 98 "gribl.l"
return CODETABLE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 99 "gribl.l"
return FLAG     ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 100 "gribl.l"
return LOOKUP   ;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "gribl.l"
return META     ;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 102 "gribl.l"
return PADTOEVEN    ;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 103 "gribl.l"
return PADTO    ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 104 "gribl.l"
return PADTOMULTIPLE    ;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 105 "gribl.l"
return PAD      ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 106 "gribl.l"
return SECTION_PADDING      ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 107 "gribl.l"
return ALIAS    ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 108 "gribl.l"
return UNALIAS    ;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 109 "gribl.l"
return POS      ;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 110 "gribl.l"
return INTCONST ;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 111 "gribl.l"
return TRANS    ;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 112 "gribl.l"
return STRING_TYPE   ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 113 "gribl.l"
return LONG_TYPE   ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 114 "gribl.l"
return ITERATOR ;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 115 "gribl.l"
return NEAREST ;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 116 "gribl.l"
return BOX ;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 117 "gribl.l"
return KSEC    ;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 118 "gribl.l"
return FLAGBIT    ;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 119 "gribl.l"
return KSEC1EXPVER    ;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "gribl.l"
return MODIFY    ;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "gribl.l"
return G1_HALF_BYTE    ;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 123 "gribl.l"
return G1_MESSAGE_LENGTH    ;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 124 "gribl.l"
return G1_SECTION4_LENGTH    ;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 126 "gribl.l"
return EXPORT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "gribl.l"
return REMOVE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 129 "gribl.l"
return SECTION_LENGTH     ;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "gribl.l"
return ASSERT    ;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "gribl.l"
return READ_ONLY;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "gribl.l"
return NO_COPY;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "gribl.l"
return EDITION_SPECIFIC;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "gribl.l"
return DUMP;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 137 "gribl.l"
return NO_FAIL;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 138 "gribl.l"
return HIDDEN;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 139 "gribl.l"
return CAN_BE_MISSING;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 140 "gribl.l"
return MISSING;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "gribl.l"
return CONSTRAINT;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 142 "gribl.l"
return OVERRIDE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "gribl.l"
return COPY_OK;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "gribl.l"
return SET;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "gribl.l"
return SET_NOFAIL;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "gribl.l"
return WHEN;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "gribl.l"
return CASE;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 149 "gribl.l"
return SWITCH;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 150 "gribl.l"
return DEFAULT;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "gribl.l"
return CONCEPT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "gribl.l"
return CONCEPT_NOFAIL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 153 "gribl.l"
return WRITE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 154 "gribl.l"
return APPEND;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 155 "gribl.l"
return PRINT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 156 "gribl.l"
return SKIP;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "gribl.l"
{
          int c,q;
          while((c = input()) && isspace(c) && c != '\n') ;
          q = c; /* the quote */

          grib_yyleng = 0;
          while((c = input()) && c != q && c != '\n')
                {
                    if(c == '\\') grib_yytext[grib_yyleng++] = input();
                    else grib_yytext[grib_yyleng++] =  c;
                }

                grib_yytext[grib_yyleng++] = 0;

          grib_parser_include(grib_yytext);
         }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 175 "gribl.l"
{
           int c,q = grib_yytext[0];

           grib_yyleng = 0;

           while((c = input()) && c != q && c != '\n')
           {
               if(c == '\\') grib_yytext[grib_yyleng++] = input();
               else grib_yytext[grib_yyleng++] =  c;
            }

            grib_yytext[grib_yyleng++] = 0;
            grib_yylval.str = strdup(grib_yytext);
            return STRING;
        }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 191 "gribl.l"
{
           int c;
           unsigned long val = 0;

           while((c = input()) && c != '`' && c != '\n')
           {
                val <<= 8;
                val |= c;
           }
           grib_yylval.lval = val;
           return INTEGER;
        }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 205 "gribl.l"
{ grib_yylval.str = strdup(grib_yytext); return IDENT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 206 "gribl.l"
{ grib_yylval.lval = atol((const char *)grib_yytext); return INTEGER; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 207 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 208 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 209 "gribl.l"
{ grib_yylval.dval = atof((const char *)grib_yytext); return FLOAT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 212 "gribl.l"
{
           int c;
           while((c = input()) && (c != '\n')){}

        grib_yylineno++;
        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 218 "gribl.l"
;
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 219 "gribl.l"
grib_yylineno++;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 223 "gribl.l"
return *grib_yytext;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 225 "gribl.l"
ECHO;
	YY_BREAK
#line 1910 "lex.grib_yy.c"
case YY_STATE_EOF(INITIAL):
	grib_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int grib_yy_amount_of_matched_text = (int) (grib_yy_cp - (grib_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*grib_yy_cp = (grib_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed grib_yyin at a new source and called
			 * grib_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file = grib_yyin;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for grib_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since grib_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (grib_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			{ /* This was really a NUL. */
			grib_yy_state_type grib_yy_next_state;

			(grib_yy_c_buf_p) = (grib_yytext_ptr) + grib_yy_amount_of_matched_text;

			grib_yy_current_state = grib_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * grib_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			grib_yy_next_state = grib_yy_try_NUL_trans( grib_yy_current_state );

			grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;

			if ( grib_yy_next_state )
				{
				/* Consume the NUL. */
				grib_yy_cp = ++(grib_yy_c_buf_p);
				grib_yy_current_state = grib_yy_next_state;
				goto grib_yy_match;
				}

			else
				{
				grib_yy_cp = (grib_yy_c_buf_p);
				goto grib_yy_find_action;
				}
			}

		else switch ( grib_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(grib_yy_did_buffer_switch_on_eof) = 0;

				if ( grib_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * grib_yy_get_next_buffer() to have set up
					 * grib_yytext, we can now set up
					 * grib_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + YY_MORE_ADJ;

					grib_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(grib_yy_c_buf_p) =
					(grib_yytext_ptr) + grib_yy_amount_of_matched_text;

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_match;

			case EOB_ACT_LAST_MATCH:
				(grib_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)];

				grib_yy_current_state = grib_yy_get_previous_state(  );

				grib_yy_cp = (grib_yy_c_buf_p);
				grib_yy_bp = (grib_yytext_ptr) + YY_MORE_ADJ;
				goto grib_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of grib_yylex */

/* grib_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int grib_yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf;
	register char *source = (grib_yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (grib_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (grib_yy_c_buf_p) - (grib_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((grib_yy_c_buf_p) - (grib_yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int grib_yy_c_buf_p_offset =
				(int) ((grib_yy_c_buf_p) - b->grib_yy_ch_buf);

			if ( b->grib_yy_is_our_buffer )
				{
				int new_size = b->grib_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->grib_yy_buf_size += b->grib_yy_buf_size / 8;
				else
					b->grib_yy_buf_size *= 2;

				b->grib_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					grib_yyrealloc((void *) b->grib_yy_ch_buf,b->grib_yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->grib_yy_ch_buf = 0;

			if ( ! b->grib_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(grib_yy_c_buf_p) = &b->grib_yy_ch_buf[grib_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move]),
			(grib_yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	if ( (grib_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			grib_yyrestart(grib_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->grib_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(grib_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(grib_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[0];

	return ret_val;
}

/* grib_yy_get_previous_state - get the state just before the EOB char was reached */

    static grib_yy_state_type grib_yy_get_previous_state (void)
{
	register grib_yy_state_type grib_yy_current_state;
	register char *grib_yy_cp;
    
	grib_yy_current_state = (grib_yy_start);

	for ( grib_yy_cp = (grib_yytext_ptr) + YY_MORE_ADJ; grib_yy_cp < (grib_yy_c_buf_p); ++grib_yy_cp )
		{
		register YY_CHAR grib_yy_c = (*grib_yy_cp ? grib_yy_ec[YY_SC_TO_UI(*grib_yy_cp)] : 1);
		if ( grib_yy_accept[grib_yy_current_state] )
			{
			(grib_yy_last_accepting_state) = grib_yy_current_state;
			(grib_yy_last_accepting_cpos) = grib_yy_cp;
			}
		while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
			{
			grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
			if ( grib_yy_current_state >= 509 )
				grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
			}
		grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
		}

	return grib_yy_current_state;
}

/* grib_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = grib_yy_try_NUL_trans( current_state );
 */
    static grib_yy_state_type grib_yy_try_NUL_trans  (grib_yy_state_type grib_yy_current_state )
{
	register int grib_yy_is_jam;
    	register char *grib_yy_cp = (grib_yy_c_buf_p);

	register YY_CHAR grib_yy_c = 1;
	if ( grib_yy_accept[grib_yy_current_state] )
		{
		(grib_yy_last_accepting_state) = grib_yy_current_state;
		(grib_yy_last_accepting_cpos) = grib_yy_cp;
		}
	while ( grib_yy_chk[grib_yy_base[grib_yy_current_state] + grib_yy_c] != grib_yy_current_state )
		{
		grib_yy_current_state = (int) grib_yy_def[grib_yy_current_state];
		if ( grib_yy_current_state >= 509 )
			grib_yy_c = grib_yy_meta[(unsigned int) grib_yy_c];
		}
	grib_yy_current_state = grib_yy_nxt[grib_yy_base[grib_yy_current_state] + (unsigned int) grib_yy_c];
	grib_yy_is_jam = (grib_yy_current_state == 508);

	return grib_yy_is_jam ? 0 : grib_yy_current_state;
}

    void grib_yyunput (int c, register char * grib_yy_bp )
{
	register char *grib_yy_cp;
    
    grib_yy_cp = (grib_yy_c_buf_p);

	/* undo effects of setting up grib_yytext */
	*grib_yy_cp = (grib_yy_hold_char);

	if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (grib_yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf )
			*--dest = *--source;

		grib_yy_cp += (int) (dest - source);
		grib_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars =
			(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_size;

		if ( grib_yy_cp < YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--grib_yy_cp = (char) c;

	(grib_yytext_ptr) = grib_yy_bp;
	(grib_yy_hold_char) = *grib_yy_cp;
	(grib_yy_c_buf_p) = grib_yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int grib_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(grib_yy_c_buf_p) = (grib_yy_hold_char);

	if ( *(grib_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* grib_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (grib_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->grib_yy_ch_buf[(grib_yy_n_chars)] )
			/* This was really a NUL. */
			*(grib_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (grib_yy_c_buf_p) - (grib_yytext_ptr);
			++(grib_yy_c_buf_p);

			switch ( grib_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because grib_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					grib_yyrestart(grib_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( grib_yywrap( ) )
						return EOF;

					if ( ! (grib_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return grib_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(grib_yy_c_buf_p) = (grib_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (grib_yy_c_buf_p);	/* cast for 8-bit char's */
	*(grib_yy_c_buf_p) = '\0';	/* preserve grib_yytext */
	(grib_yy_hold_char) = *++(grib_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void grib_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        grib_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            grib_yy_create_buffer(grib_yyin,YY_BUF_SIZE );
	}

	grib_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	grib_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void grib_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		grib_yypop_buffer_state();
	 *		grib_yypush_buffer_state(new_buffer);
     */
	grib_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	grib_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (grib_yywrap()) processing, but the only time this flag
	 * is looked at is after grib_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

static void grib_yy_load_buffer_state  (void)
{
    	(grib_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars;
	(grib_yytext_ptr) = (grib_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos;
	grib_yyin = YY_CURRENT_BUFFER_LVALUE->grib_yy_input_file;
	(grib_yy_hold_char) = *(grib_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE grib_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_buf_size = size;

	/* grib_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->grib_yy_ch_buf = (char *) grib_yyalloc(b->grib_yy_buf_size + 2  );
	if ( ! b->grib_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_create_buffer()" );

	b->grib_yy_is_our_buffer = 1;

	grib_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with grib_yy_create_buffer()
 * 
 */
    void grib_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->grib_yy_is_our_buffer )
		grib_yyfree((void *) b->grib_yy_ch_buf  );

	grib_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a grib_yyrestart() or at EOF.
 */
    static void grib_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	grib_yy_flush_buffer(b );

	b->grib_yy_input_file = file;
	b->grib_yy_fill_buffer = 1;

    /* If b is the current buffer, then grib_yy_init_buffer was _probably_
     * called from grib_yyrestart() or through grib_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->grib_yy_bs_lineno = 1;
        b->grib_yy_bs_column = 0;
    }

        b->grib_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void grib_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->grib_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->grib_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->grib_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->grib_yy_buf_pos = &b->grib_yy_ch_buf[0];

	b->grib_yy_at_bol = 1;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		grib_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void grib_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	grib_yyensure_buffer_stack();

	/* This block is copied from grib_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(grib_yy_c_buf_p) = (grib_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_buf_pos = (grib_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->grib_yy_n_chars = (grib_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(grib_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from grib_yy_switch_to_buffer. */
	grib_yy_load_buffer_state( );
	(grib_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void grib_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	grib_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((grib_yy_buffer_stack_top) > 0)
		--(grib_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		grib_yy_load_buffer_state( );
		(grib_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void grib_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(grib_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyalloc
								(num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);
		
		memset((grib_yy_buffer_stack), 0, num_to_alloc * sizeof(struct grib_yy_buffer_state*));
				
		(grib_yy_buffer_stack_max) = num_to_alloc;
		(grib_yy_buffer_stack_top) = 0;
		return;
	}

	if ((grib_yy_buffer_stack_top) >= ((grib_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (grib_yy_buffer_stack_max) + grow_size;
		(grib_yy_buffer_stack) = (struct grib_yy_buffer_state**)grib_yyrealloc
								((grib_yy_buffer_stack),
								num_to_alloc * sizeof(struct grib_yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((grib_yy_buffer_stack) + (grib_yy_buffer_stack_max), 0, grow_size * sizeof(struct grib_yy_buffer_state*));
		(grib_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE grib_yy_scan_buffer  (char * base, grib_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) grib_yyalloc(sizeof( struct grib_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_buffer()" );

	b->grib_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->grib_yy_buf_pos = b->grib_yy_ch_buf = base;
	b->grib_yy_is_our_buffer = 0;
	b->grib_yy_input_file = 0;
	b->grib_yy_n_chars = b->grib_yy_buf_size;
	b->grib_yy_is_interactive = 0;
	b->grib_yy_at_bol = 1;
	b->grib_yy_fill_buffer = 0;
	b->grib_yy_buffer_status = YY_BUFFER_NEW;

	grib_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to grib_yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       grib_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE grib_yy_scan_string (grib_yyconst char * grib_yystr )
{
    
	return grib_yy_scan_bytes(grib_yystr,strlen(grib_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to grib_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE grib_yy_scan_bytes  (grib_yyconst char * grib_yybytes, int  _grib_yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	grib_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _grib_yybytes_len + 2;
	buf = (char *) grib_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in grib_yy_scan_bytes()" );

	for ( i = 0; i < _grib_yybytes_len; ++i )
		buf[i] = grib_yybytes[i];

	buf[_grib_yybytes_len] = buf[_grib_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = grib_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in grib_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->grib_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void grib_yy_fatal_error (grib_yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine grib_yyless() so it works in section 3 code. */

#undef grib_yyless
#define grib_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up grib_yytext. */ \
        int grib_yyless_macro_arg = (n); \
        YY_LESS_LINENO(grib_yyless_macro_arg);\
		grib_yytext[grib_yyleng] = (grib_yy_hold_char); \
		(grib_yy_c_buf_p) = grib_yytext + grib_yyless_macro_arg; \
		(grib_yy_hold_char) = *(grib_yy_c_buf_p); \
		*(grib_yy_c_buf_p) = '\0'; \
		grib_yyleng = grib_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the input stream.
 * 
 */
FILE *grib_yyget_in  (void)
{
        return grib_yyin;
}

/** Get the output stream.
 * 
 */
FILE *grib_yyget_out  (void)
{
        return grib_yyout;
}

/** Get the length of the current token.
 * 
 */
int grib_yyget_leng  (void)
{
        return grib_yyleng;
}

/** Get the current token.
 * 
 */

char *grib_yyget_text  (void)
{
        return grib_yytext;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see grib_yy_switch_to_buffer
 */
void grib_yyset_in (FILE *  in_str )
{
        grib_yyin = in_str ;
}

void grib_yyset_out (FILE *  out_str )
{
        grib_yyout = out_str ;
}

int grib_yyget_debug  (void)
{
        return grib_yy_flex_debug;
}

void grib_yyset_debug (int  bdebug )
{
        grib_yy_flex_debug = bdebug ;
}

static int grib_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from grib_yylex_destroy(), so don't allocate here.
     */

    (grib_yy_buffer_stack) = 0;
    (grib_yy_buffer_stack_top) = 0;
    (grib_yy_buffer_stack_max) = 0;
    (grib_yy_c_buf_p) = (char *) 0;
    (grib_yy_init) = 0;
    (grib_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    grib_yyin = stdin;
    grib_yyout = stdout;
#else
    grib_yyin = (FILE *) 0;
    grib_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * grib_yylex_init()
     */
    return 0;
}

/* grib_yylex_destroy is for both reentrant and non-reentrant scanners. */
int grib_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		grib_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		grib_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	grib_yyfree((grib_yy_buffer_stack) );
	(grib_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * grib_yylex() is called, initialization will occur. */
    grib_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef grib_yytext_ptr
static void grib_yy_flex_strncpy (char* s1, grib_yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int grib_yy_flex_strlen (grib_yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *grib_yyalloc (grib_yy_size_t  size )
{
	return (void *) malloc( size );
}

void *grib_yyrealloc  (void * ptr, grib_yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void grib_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see grib_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "grib_yytables"

#line 225 "gribl.l"




